# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myproto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'myproto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\" \n\x0cRoverRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"\x1a\n\x0bMapResponse\x12\x0b\n\x03map\x18\x01 \x01(\t\"#\n\x0f\x43ommandResponse\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"+\n\x12MineSerialResponse\x12\x15\n\rserial_number\x18\x01 \x01(\t2\xa1\x01\n\rGroundControl\x12%\n\x06GetMap\x12\r.RoverRequest\x1a\x0c.MapResponse\x12.\n\x0bGetCommands\x12\r.RoverRequest\x1a\x10.CommandResponse\x12\x39\n\x13GetMineSerialNumber\x12\r.RoverRequest\x1a\x13.MineSerialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROVERREQUEST']._serialized_start=17
  _globals['_ROVERREQUEST']._serialized_end=49
  _globals['_MAPRESPONSE']._serialized_start=51
  _globals['_MAPRESPONSE']._serialized_end=77
  _globals['_COMMANDRESPONSE']._serialized_start=79
  _globals['_COMMANDRESPONSE']._serialized_end=114
  _globals['_MINESERIALRESPONSE']._serialized_start=116
  _globals['_MINESERIALRESPONSE']._serialized_end=159
  _globals['_GROUNDCONTROL']._serialized_start=162
  _globals['_GROUNDCONTROL']._serialized_end=323
# @@protoc_insertion_point(module_scope)
